### ISSUE TITLE
Support `Windows.UI.UIAutomation` APIs

### ISSUE THREAD

**Issue by xgwang-scienceos** [dart-windows/dartwinrt#204]
Hello, I came across two questions regarding UI Automation APIs:

1) if I'd like to access the WinRT APIs in the Microsoft.UI.Automation namespace, it this the right project to make feature a request and/or make contributions? 

2) if the answer for 1) is no, what is the recommended way of consuming C++ libraries in dart?

Thanks!

**Comment by halildurmus** [comment]
> 1. if I'd like to access the WinRT APIs in the Microsoft.UI.Automation namespace, it this the right project to make feature a request and/or make contributions?

Could you please provide me with a link to the WinRT APIs that you referring to? I could not find any information about them. 

Please note that the WinRT namespaces always start with `Windows.`.  [Here](https://learn.microsoft.com/en-us/uwp/api/) is the link that provides a comprehensive list of all WinRT namespaces.

It's possible that you are referring to the WinRT APIs from [Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/), which their namespaces start with `Microsoft.`. However, supporting the WinRT APIs from the Windows App SDK is not within the scope of this project.

**Comment by xgwang-scienceos** [comment]
@halildurmus Thanks for the quick followup! [This](https://github.com/microsoft/Microsoft-UI-UIAutomation#:~:text=The%20bulk%20of%20the%20Remote%20Operations%20helper%20code%20is%20in%20a%20WinRT%20API%20exposed%20by%20the%20Microsoft.UI.UIAutomation%20DLL) is where I got the `Microsoft.UI.Automation` namespace from. 

That seems to be a wrapper of the `Windows.UI.UIAutomation` namespace APIs, consumable from C++/WinRT. 

So question 1) can be reframed to: if I'd like to access APIs in the Windows.UI.Automation namespace, it this the right project to make feature a request and/or make contributions?

**Comment by xgwang-scienceos** [comment]
Thanks a lot! Would you like to keep this topic open for tracking purpose or close it for now?
